# Generated by Django 6.0.2 on 2026-02-10 09:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('logo_url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_hospitals', to='staff.appuser')),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital.hospital')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospital.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'hospital_reviews',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_staff_count', models.PositiveIntegerField()),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('shift_type', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('ON_CALL', 'On Call')], default='DAY', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='hospital.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='hospital.hospital')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='staff.profession')),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=16)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='staff.staffprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hospital.jobposting')),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=16)),
                ('shift_start_snapshot', models.DateTimeField()),
                ('shift_end_snapshot', models.DateTimeField()),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to='staff.appuser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospital.jobposting')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'shift_assignments',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PARTIAL', 'Partial')], default='PRESENT', max_length=16)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hospital.shiftassignment')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='StaffHospitalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_affiliations', to='hospital.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_affiliations', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_hospital_affiliations',
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_department_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='hospitalreview',
            constraint=models.UniqueConstraint(fields=('staff', 'hospital'), name='unique_staff_hospital_review'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('shift_start__lt', models.F('shift_end'))), name='job_posting_shift_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('required_staff_count__gt', 0)), name='job_posting_required_staff_positive'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'staff'), name='unique_job_staff_application'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('job', 'staff'), name='unique_job_staff_assignment'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('shift_start_snapshot__lt', models.F('shift_end_snapshot'))), name='assignment_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='staffhospitalaffiliation',
            constraint=models.UniqueConstraint(fields=('staff', 'hospital'), name='unique_staff_hospital_affiliation'),
        ),
    ]
